Vagrant.configure(2) do |config|

  config.vm.box = "debian/contrib-jessie64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.network "private_network", ip: "192.168.123.11"

  config.vm.provision :shell, :path => "provision.sh"

end
