FROM node:4.4
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./src /usr/src/app/
RUN npm install
CMD [ "npm", "start" ]

TODO: Use fullfeatured base image and install node on it / try other node images
